version: "3.7"

services:
    server:
        container_name: server
        restart: always
        build: ./server
        ports:
            - "8080:8080"
        depends_on:
            - database
        networks:
            - app-network
    database:
        container_name: database
        image: mongo
        volumes:
            - ./database/data:/data/db
        ports:
            - "27017:27017"
        networks:
            - app-network
    client:
        container_name: client
        build: ./client
        depends_on:
            - server
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - "80:80"
        networks:
            - app-network

    #    rabbitmq:
    #        image: rabbitmq:3-management-alpine
    #        container_name: rabbitmq
    #        volumes:
    #            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    #        environment:
    #            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    #            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    #            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    #        ports:
    #            - 5672:5672
    #            - 15672:15672

networks:
    app-network:
        driver: bridge